---
apiVersion: v1
data:
  client.yaml: dmVyc2lvbjogIiIKc3NsOiB0cnVlCmNhY2VydHBhdGg6IC9ldGMvYml0ZnVzaW9uL3Rscy9jYS5jcnQKa2V5cGF0aDogL2V0Yy9iaXRmdXNpb24vdGxzL2JpdGZ1c2lvbi5rZXkKY2VydHBhdGg6IC9ldGMvYml0ZnVzaW9uL3Rscy9iaXRmdXNpb24uY3J0CmRiY2VydHBhdGg6IC9ldGMvYml0ZnVzaW9uL3Rscy9jYS5jcnQKbWluLXRscy12ZXJzaW9uOiAiIgp0aW1lb3V0OiAzcwphdXRoY29uZmlnOgogIGVuYWJsZWQ6IHRydWUKICB1c2VybmFtZTogIiIKICBwYXNzd29yZDogIiIKICBkYnVzZXJuYW1lOiAiIgogIGRicGFzc3dvcmQ6ICIiCiAgdG9rZW46IENXVlVINlhQVkpDQ0NTU0JLM1pWRkw2NDRFUzdFWFhQU0VJRVlBN0ZIWFE3VkJXT09CQjdLNUdITVVGWlg2QktWUVNMQ09ZWVRaTEVKS1NaS0MyR0NESFA1UzVZRFFGM00yUEpaTDZJVFNVNkdZNjZBTEtQTVhaSExSNFI1S0w0Cm5ldHdvcms6IHt9CmRpc3BhdGNoZXI6CiAgYWN0aXZhdGVkOiB0cnVlCiAgc3JzOgogICAgYXV0b19yZWxlYXNlX3RpbWVvdXQ6IDEwbQogIGNhY2hlX3N0b3JlOgogICAgY2xpZW50X3Jvb3Q6IC9ob21lL2JpdGZ1c2lvbi8uYml0ZnVzaW9uL2NhY2hlCiAgICBjbGllbnRfY2xlYW51cF90aHJlc2hvbGRfTUI6IDUxMjAKICAgIHNlcnZlcl9yb290OiAvdmFyL2NhY2hlL2JpdGZ1c2lvbgogICAgc2VydmVyX2NsZWFudXBfdGhyZXNob2xkX01COiA1MTIwCg==
kind: Secret
metadata:
  name: bitfusion-client-secret-client.yml
  #namespace: k8s-papivot-tools
  namespace: k8s-papivot-tools-bf
type: Opaque
